// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPfbydpHhP-vnfj--L1jzJyEqLFb1-Tx8',
    appId: '1:208649506339:web:75212330db48dfaaa3eb96',
    messagingSenderId: '208649506339',
    projectId: 'bong-bae',
    authDomain: 'bong-bae.firebaseapp.com',
    storageBucket: 'bong-bae.firebasestorage.app',
    measurementId: 'G-NZLXX2ZR4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOGoIAEvkunohIKrk6k1QTOndbPWQmNDo',
    appId: '1:208649506339:android:2165c31587573811a3eb96',
    messagingSenderId: '208649506339',
    projectId: 'bong-bae',
    storageBucket: 'bong-bae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmWWb4cqA13Up-NSQLKeMQU9fMS0_Sf1w',
    appId: '1:208649506339:ios:be2ab6756c4f1a3fa3eb96',
    messagingSenderId: '208649506339',
    projectId: 'bong-bae',
    storageBucket: 'bong-bae.firebasestorage.app',
    iosBundleId: 'com.example.bongbae',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmWWb4cqA13Up-NSQLKeMQU9fMS0_Sf1w',
    appId: '1:208649506339:ios:be2ab6756c4f1a3fa3eb96',
    messagingSenderId: '208649506339',
    projectId: 'bong-bae',
    storageBucket: 'bong-bae.firebasestorage.app',
    iosBundleId: 'com.example.bongbae',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPfbydpHhP-vnfj--L1jzJyEqLFb1-Tx8',
    appId: '1:208649506339:web:2cc521c4c4c51d7aa3eb96',
    messagingSenderId: '208649506339',
    projectId: 'bong-bae',
    authDomain: 'bong-bae.firebaseapp.com',
    storageBucket: 'bong-bae.firebasestorage.app',
    measurementId: 'G-1DFJYQ4PB9',
  );
}
